### ISSUE TITLE
 Synchronization block failed

### ISSUE THREAD

**Issue by satonz** [JINWOO-J/prep_docker#55]
![image](https://user-images.githubusercontent.com/38401802/93172246-0f5d1880-f75d-11ea-92dd-1efc2d4c17c3.png)

How should I handle it

**Comment by JINWOO-J** [comment]
It's hard to know the exact reason just from the log you showed.
First, change the latest docker image version.

Latest Version : **iconloop / prep-node: 2009031457xdaf395**

**Comment by satonz** [comment]
Thank you, this problem is really because I am using the wrong version
